"""配置中心的服务类型与字段定义；这里只描述表单，不含连接或认证行为。"""
from __future__ import annotations
from copy import deepcopy

FIELDS = {
    'description': {'label':'说明','multiline':True},
    'account': {'label':'账户'},
    'password': {'label':'密码','sensitive':True},
    'host': {'label':'主机'},
    'ip': {'label':'IP 地址'},
    'port': {'label':'端口','value_type':'integer'},
    'endpoint': {'label':'服务地址'},
    'remote_path': {'label':'路径'},
    'database_type': {'label':'数据库类型','options':['PostgreSQL','MySQL','SQL Server','Oracle','MariaDB','其他']},
    'database': {'label':'数据库 / 实例名'},
    'namespace': {'label':'命名空间'},
    'group': {'label':'配置分组'},
    'access_key': {'label':'Access Key','sensitive':True},
    'secret_key': {'label':'Secret Key','sensitive':True},
    'bucket': {'label':'Bucket'},
    'region': {'label':'Region'},
    'app_id': {'label':'应用 ID'},
    'key': {'label':'API Key','sensitive':True},
    'token': {'label':'Token','sensitive':True},
    'private_key': {'label':'私钥','sensitive':True,'multiline':True},
    'public_key': {'label':'公钥','multiline':True},
    'passphrase': {'label':'私钥口令','sensitive':True},
    'certificate': {'label':'证书','multiline':True},
    'database_index': {'label':'数据库索引','value_type':'integer','minimum':0,'maximum':2147483647},
    'connection_mode': {'label':'连接模式','options':['单机','哨兵','集群']},
    'endpoints': {'label':'节点地址','multiline':True},
    'sentinel_master': {'label':'Sentinel 主节点名称'},
    'auth_database': {'label':'认证数据库'},
    'replica_set': {'label':'副本集'},
    'connection_uri': {'label':'连接 URI','sensitive':True},
    'brokers': {'label':'Broker 地址','multiline':True},
    'security_protocol': {'label':'安全协议','options':['PLAINTEXT','SSL','SASL_PLAINTEXT','SASL_SSL']},
    'sasl_mechanism': {'label':'SASL 机制','options':['PLAIN','SCRAM-SHA-256','SCRAM-SHA-512','GSSAPI','OAUTHBEARER']},
    'virtual_host': {'label':'Virtual Host'},
    'name_servers': {'label':'NameServer 地址','multiline':True},
    'kubeconfig': {'label':'Kubeconfig','sensitive':True,'multiline':True},
    'transport_security': {'label':'传输加密','options':['TLS','STARTTLS','无']},
    'extra_config': {'label':'补充配置','sensitive':True,'multiline':True},
}
TYPES = [
    {'id':'database','label':'数据库','sections':[{'label':'连接信息','fields':['database_type','host','ip','port','database']},{'label':'账户信息','fields':['account','password']}]},
    {'id':'redis','label':'Redis','sections':[{'label':'连接信息','fields':['connection_mode','host','ip','port','database_index','endpoints','sentinel_master']},{'label':'账户信息','fields':['account','password']}]},
    {'id':'mongodb','label':'MongoDB','sections':[{'label':'连接信息','fields':['host','port','database','auth_database','replica_set','connection_uri']},{'label':'账户信息','fields':['account','password']}]},
    {'id':'nacos','label':'Nacos','sections':[{'label':'服务信息','fields':['endpoint','namespace','group']},{'label':'账户信息','fields':['account','password']}]},
    {'id':'s3','label':'S3 / 对象存储','sections':[{'label':'服务信息','fields':['endpoint','bucket','region']},{'label':'访问凭证','fields':['access_key','secret_key']}]},
    {'id':'dify','label':'Dify','sections':[{'label':'服务与应用','fields':['endpoint','app_id']},{'label':'账户与接口凭证','fields':['account','password','key']}]},
    {'id':'kafka','label':'Kafka','sections':[{'label':'集群信息','fields':['brokers','security_protocol','sasl_mechanism']},{'label':'访问凭证','fields':['account','password','certificate']}]},
    {'id':'rabbitmq','label':'RabbitMQ','sections':[{'label':'服务信息','fields':['host','port','virtual_host','endpoint']},{'label':'账户信息','fields':['account','password']}]},
    {'id':'rocketmq','label':'RocketMQ','sections':[{'label':'服务信息','fields':['name_servers','endpoint','namespace']},{'label':'访问凭证','fields':['access_key','secret_key']}]},
    {'id':'search','label':'Elasticsearch / OpenSearch','sections':[{'label':'服务信息','fields':['endpoint']},{'label':'访问凭证','fields':['account','password','key','certificate']}]},
    {'id':'ssh','label':'SSH 主机','sections':[{'label':'主机信息','fields':['host','ip','port','remote_path']},{'label':'认证信息','fields':['account','password','private_key','passphrase']}]},
    {'id':'registry','label':'容器镜像仓库','sections':[{'label':'仓库信息','fields':['endpoint','namespace']},{'label':'访问凭证','fields':['account','password','token']}]},
    {'id':'kubernetes','label':'Kubernetes','sections':[{'label':'集群信息','fields':['endpoint','namespace']},{'label':'访问凭证','fields':['kubeconfig','token','certificate','private_key']}]},
    {'id':'gitlab','label':'GitLab','sections':[{'label':'服务信息','fields':['endpoint','account']},{'label':'访问凭证','fields':['token']}]},
    {'id':'jenkins','label':'Jenkins','sections':[{'label':'服务信息','fields':['endpoint','account']},{'label':'访问凭证','fields':['token','password']}]},
    {'id':'smtp','label':'SMTP 邮件服务','sections':[{'label':'服务信息','fields':['host','port','transport_security']},{'label':'账户信息','fields':['account','password']}]},
    {'id':'service','label':'其他服务','sections':[{'label':'服务信息','fields':['host','ip','port','endpoint','remote_path']},{'label':'账户信息','fields':['account','password','key']}]},
    {'id':'github','label':'GitHub','sections':[{'label':'服务信息','fields':['endpoint','account']},{'label':'访问凭证','fields':['token']}]},
    {'id':'key_material','label':'GPG / SSH 密钥','sections':[{'label':'密钥材料','fields':['public_key','private_key','passphrase','certificate']}]},
    {'id':'api','label':'API 接口','sections':[{'label':'接口与凭证','fields':['endpoint','account','key','token']}]},
    {'id':'postgresql','label':'PostgreSQL','sections':[{'label':'连接信息','fields':['host','ip','port','database']},{'label':'账户信息','fields':['account','password']}]},
    {'id':'file_server','label':'文件服务器','sections':[{'label':'服务信息','fields':['endpoint','host','port','remote_path']},{'label':'访问凭证','fields':['account','password','private_key','passphrase']}]},
    {'id':'gitee','label':'Gitee','sections':[{'label':'仓库信息','fields':['endpoint','account']},{'label':'访问凭证','fields':['token','private_key','passphrase']}]},
    {'id':'gpg','label':'GPG','sections':[{'label':'密钥材料','fields':['public_key','private_key','passphrase']}]},
    {'id':'frontend_release','label':'前端发布','sections':[{'label':'发布目标','fields':['endpoint','host','port','remote_path']},{'label':'发布凭证','fields':['account','token','private_key','passphrase']},{'label':'构建与发布配置','fields':['extra_config']}]},
    {'id':'backend_release','label':'后端发布','sections':[{'label':'发布目标','fields':['endpoint','host','port','remote_path','namespace']},{'label':'发布凭证','fields':['account','token','private_key','passphrase']},{'label':'构建与发布配置','fields':['extra_config']}]},
    {'id':'general','label':'通用配置','sections':[{'label':'基本字段','fields':['endpoint','account','password','key','token']},{'label':'扩展内容','fields':['extra_config']}]},
]

def configuration_schema() -> dict:
    """返回可安全展示的字段定义副本；环境与分类使用用户明确选择的组织标签。"""
    return {'types':deepcopy(TYPES),'fields':deepcopy(FIELDS),
            'common_fields':['description','extra_config'],
            'groups':[{'label':'数据与缓存','types':['database','postgresql','redis','mongodb','s3','file_server','search']},{'label':'消息与应用','types':['nacos','dify','kafka','rabbitmq','rocketmq','smtp']},{'label':'研发与部署','types':['github','gitee','gitlab','jenkins','ssh','registry','kubernetes','frontend_release','backend_release']},{'label':'密钥与通用','types':['key_material','gpg','api','service','general']}],
            'environments':[{'id':'development','label':'开发'},{'id':'production','label':'生产'},{'id':'shared','label':'通用'}]}
